### ISSUE TITLE
Possibilitar alternar entre diferentes moedas.

### ISSUE THREAD

**Issue by cfviotti** [dolarnubank/dolarnubank.github.io#2]
Seria interessante simular o valor de compra em outras moedas. Alguma noção de como é a conversão do Nubank para estes casos?
Já fiz uma compra em Euro e o aplicativo me dava como referência ainda o valor do dólar PTAX, que não dizia muita coisa no fim das contas.

**Comment by gabrielbarros** [comment]
🚫

https://pastebin.com/raw/WBjMYLmw
